// client/src/Login.svelte
<script>
    import axios from 'axios';
    import page from 'page';
    import {getContext, setContext} from 'svelte';

    const endpoint = getContext('endpoint');
    let error = null;
    let email = '';
    let password = '';

    async function handleSubmit() {
        try {
            const response = await axios.post(
                `${endpoint}/login`, {email, password}
            );
            const creds = {userId: response.data.userId, apikey: response.data.apikey};
            window.localStorage.setItem('creds', JSON.stringify(creds));
            page('/home');
            location.reload();  // Force the new context to get set
        } catch (ex) {
            error = ex.response.data.error;
        }
    }
</script>

<form on:submit|preventDefault={handleSubmit}>
    <header class="font-bold">Log In</header>

    {#if error}<p>{error}</p>{/if}

    <label>
        Username:
        <input
            type="email"
            placeholder="username"
            class="border w-full"
            bind:value={email}
            required
        />
    </label>

    <label>
        Password
        <input
            type="password"
            placeholder="password"
            class="bordre w-full"
            bind:value={password}
            required
        />
    </label>

    <button type="submit" class='btn btn-primary'>Log In</button><button>
</form>

// client.vue/src/views/Login.vue
<template>
  <form v-on:submit.prevent="handleSubmit" class="content">
    <header class='font-bold'>Log In</header>

    <p v-if='error'>{{error}}</p>

    <label>
      Email
      <input
        type='email'
        placeholder='you@example.com'
        class='border w-full'
        v-model='email'
        required
      />
    </label>

    <label>
      Password
      <input
        type='password'
        placeholder='password'
        class='border w-full'
        v-model='password'
        required
      />
    </label>

    <button type='submit' class='btn btn-primary'>Log In</button>
  </form>
</template>

<script lang="ts">
import axios from 'axios';
import Vue from 'vue'

import {endpoint} from '../lib/config';

export default Vue.extend({
  data() {
    return {
      error: null,
      email: '',
      password: '',
      endpoint,
    };
  },

  methods: {
    async handleSubmit() {
      try {
        const response = await axios.post(
          `${endpoint}/login`, {email: this.email, password: this.password}
        );
        const creds = {userId: response.data.userId, apikey: response.data.apikey};
        window.localStorage.setItem('creds', JSON.stringify(creds));
        this.$router.push('home');
        location.reload();  // Force the new context to get set
      } catch (ex) {
        this.error = ex.response.data.error;
      }

    }
  },
})
</script>
