// client/src/components/Balance.tsx
import React from 'react';

import {Intervals} from '../lib/Accounts';
import * as Balances from '../lib/Balances';
import styles from './Balance.module.css';
import { toDollars } from '../lib/pennies';

export default function Balance({ balance, adjustment, interval }: { balance: Balances.T, adjustment?: number, interval?: Intervals }) {
  const prorated = Balances.isBalanceEnvelope(balance) ? Balances.calcAmountForPeriod(balance)[interval || 'monthly'] : 0;
  adjustment = adjustment || 0;

  return <>
    <div className='font-bold'>
      <div>{balance.name}</div>
      {Balances.isBalanceEnvelope(balance) ?
        <progress
          className={balance.balance < 0 ? styles.ProgressFlipped : styles.Progress}
          value={Math.abs(balance.balance) + adjustment}
          max={balance.extra.target || 0}
        />
        : null
      }
    </div>
    <div>
      <div className='text-right'>{toDollars(balance.balance + adjustment)}</div>
      {Balances.isBalanceEnvelope(balance) ?
        <div className='text-right text-xs italic'>
          {toDollars(prorated)} / {interval}
        </div> :
        null
      }
    </div>
  </>
}

// client/src/Balance.svelte
<script>
  import * as Balances from './lib/Balances';
  import {toDollars} from './lib/pennies';

  export let balance;
  export let adjustment = 0;
  export let interval = 'monthly'

  $: prorated =
    Balances.isBalanceEnvelope(balance) ?
    Balances.calcAmountForPeriod(balance)[interval] :
    0;
</script>

<style>
.progress-flipped {
    transform: rotate(180deg);
}

.progress-flipped::-moz-progress-bar {
    background-color: #c65e21;
}

.progress-flipped::-webkit-progress-value {
    background-color: #c65e21;
}

.progress::-moz-progress-bar {
    background-color: #7bb026;
}
.progress::-webkit-progress-value {
    background-color: #7bb026;
}

.progress[value] {
    appearance: none;
}
.progress-flipped[value] {
    appearance: none;
}

</style>

<div class="font-bold">
  <div data-cy='balance-name'>{balance.name}</div>
  {#if Balances.isBalanceEnvelope(balance)}
    <progress
      class={(balance.balance + adjustment) < 0 ? 'progress-flipped' : 'progress'}
      value={Math.abs(balance.balance) + adjustment}
      max={balance.extra.target || 0}
    />
  {/if}
</div>

<div data-cy='balance-fill-stuff'>
  <div class="text-right">{toDollars(balance.balance + adjustment)}</div>
  {#if Balances.isBalanceEnvelope(balance)}
    <div class="text-right text-xs italic">
      <span data-cy='fill-per-period'>{toDollars(prorated)}</span> / {interval}
    </div>
  {/if}
</div>
