// client/src/components/FillEnvelopes.tsx
import { RouteComponentProps } from 'react-router-dom';
import React, { useEffect, useState } from 'react';
import * as shortid from 'shortid';

import '../lib/core.css';
import { AuthStore, FlashStore } from '../store';
import Balance from './Balance';
import * as Balances from '../lib/Balances';
import { Intervals } from '../lib/Accounts';
import * as ITransactions from '../lib/ITransactions';
import MoneyInput from './MoneyInput';
import { toDollars } from '../lib/pennies';

export default function FillEnvelopes(props: RouteComponentProps<{ txnId?: string }>) {
  interface Fill { id: string, envelopeId: string; amount: number; envelope: Balances.BalanceEnvelope }
  const [fills, setFills] = useState<Fill[]>([]);
  const [interval, setInterval] = useState<Intervals>('weekly');

  function setError(msg: string) {
    FlashStore.flash = msg;
    FlashStore.type === 'error';
  }

  useEffect(() => {
    if (!AuthStore.loggedIn) throw new Error('User must be logged in');
    Balances.loadBalancess(AuthStore.userId, AuthStore.apiKey).
      then(({ data }) => {
        const newFills: Fill[] =
          data.balances.
            filter((balance) => Balances.isBalanceEnvelope(balance)).
            map((balance) => ({
              id: balance.id,
              envelopeId: balance.id,
              amount: 0,
              envelope: balance as Balances.BalanceEnvelope, // We can cast this becasue of the filter
            }));

        if (!props.match.params.txnId) {
          setFills(newFills);
          return;
        }
        if (!AuthStore.loggedIn) throw new Error('User must be logged in');
        // Load a prior fill
        return (
          ITransactions.loadTransaction(AuthStore.userId, AuthStore.apiKey, props.match.params.txnId).
            then(({ data }) => {
              if (data.transactions.length === 0) {
                props.history.push('/404');
                return;  // 404
              }

              console.log(data.transactions);
              setFills(newFills.map((fill) => {
                const priorFill = data.transactions.find((txn) => txn.to_id === fill.envelopeId);
                if (priorFill) {
                  return {
                    id: fill.id,
                    envelopeId: fill.envelopeId,
                    amount: priorFill.amount,
                    envelope: fill.envelope
                  };
                }
                return fill;
              }));
            }).catch((ex) => setError(ex.message))
        );
      }).catch((ex) => setError(ex.message));
  }, [props.match.params.txnId]);

  if (fills.length === 0) return <p>Loading...</p>;

  const unallocated = fills.find(({ envelope }) => envelope.name === '[Unallocated]');
  if (!unallocated) throw new Error('You don\'t have an [Unallocated] category!');

  function fillEnvelope(fill: Fill, amount: number) {
    setFills(fills.map((f) => {
      if (fill !== f) return f;
      return { ...f, amount }
    }));
  }

  async function handleSubmit(event: React.FormEvent<any>) {
    event.preventDefault();
    const txnId = props.match.params.txnId || shortid.generate();
    if (!AuthStore.userId) throw new Error('User must be logged in');
    const txns: ITransactions.T[] = fills.map((fill, i) => {
      if (!AuthStore.userId) throw new Error('User must be logged in');
      const txn: ITransactions.T = {
        id: shortid.generate(),
        user_id: AuthStore.userId,
        memo: '',
        date: new Date(),
        amount: Math.round(fill.amount),
        label: null,
        type: 'fill',
        txn_id: txnId,
        from_id: unallocated!.envelope.id,
        to_id: fill.envelope.id,
      };
      return txn;
    }).filter((txn) => txn.amount !== 0);

    await ITransactions.deleteTransactions(AuthStore.userId, AuthStore.apiKey, txnId);
    await ITransactions.saveTransactions(AuthStore.userId, AuthStore.apiKey, txns);
    props.history.push('/');
  }

  function sumOfFills() {
    return fills.map((fill) => fill.amount).reduce((acc, item) => acc + item, 0);
  }

  async function deleteTransaction(event: React.MouseEvent<any>) {
    event.preventDefault();
    if (!props.match.params.txnId) {
      throw new Error('Shouldn\'t be inside delete handler without a txn to delete');
    }
    if (!AuthStore.loggedIn) throw new Error('User must be logged in');
    await ITransactions.deleteTransactions(
      AuthStore.userId, AuthStore.apiKey, props.match.params.txnId
    );
    props.history.push('/');
  }

  return (
    <div className={`flex justify-around content`}>
      <form onSubmit={handleSubmit} className='bg-white p-4 rounded border border-2 border-grey-light m-4'>
        <p>Unallocated: {toDollars(unallocated.envelope.balance - sumOfFills())}</p>

        <select
          value={interval}
          onChange={(event) => setInterval(event.target.value as Intervals)}
          className='border'
        >
          <option value='weekly'>Weekly</option>
          <option value='biweekly'>Biweekly</option>
          <option value='monthly'>Monthly</option>
          <option value='annually'>Annually</option>
        </select>

        <>
          {fills.filter((fill) => fill.envelope.name !== '[Unallocated]').map((fill) =>
            <div key={fill.envelope.id} className='flex justify-between bubble'>
              <div>
                <Balance balance={fill.envelope} adjustment={fill.amount} />
                {props.match.params.txnId ? null :
                  <>
                    <button
                      onClick={(event) => { event.preventDefault(); fillEnvelope(fill, Balances.calcAmountForPeriod(fill.envelope)[interval]) }}
                      className='border'
                    >
                      Fill {toDollars(Balances.calcAmountForPeriod(fill.envelope)[interval])}
                    </button>
                    <button
                      onClick={(event) => { event.preventDefault(); fillEnvelope(fill, -fill.envelope.balance) }}
                      className='border'
                    >
                      Set to 0
                    </button>
                  </>
                }
              </div>
              <div>
                <div>Balance: {toDollars(fill.envelope.balance)}</div>
                <span>Fill:</span>
                <MoneyInput
                  default='credit'
                  startingValue={fill.amount}
                  onChange={(num) => fillEnvelope(fill, num)}
                  key={`${fill.id}-${fill.envelope.id}`}
                />
                <div>New Balance: {toDollars(fill.envelope.balance + fill.amount)}</div>
              </div>
            </div>
          )}
        </>

        {props.match.params.txnId ? <button onClick={deleteTransaction}>Delete Transaction</button> : null}

        <input type='submit' value='Fill!' className="link-btn link-btn-primary" />
      </form>
    </div>
  )
}

// client/src/FillEnvelopes.svelte
<script>
  import page from "page";
  import * as shortid from "shortid";

  import Balance from "./Balance.svelte";
  import * as Balances from "./lib/Balances";
  import MoneyInput from "./MoneyInput.svelte";
  import { toDollars } from "./lib/pennies";
  import * as Transactions from "./lib/Transactions";
  import { guardCreds } from "./lib/utils";
  import { onMount } from "svelte";

  const creds = guardCreds();

  let dataP = Promise.resolve([]);
  let fills = [];
  $: sumOfFills = fills
    .map(fill => fill.amount)
    .reduce((acc, item) => acc + item, 0);
  $: unallocated = fills.find(fill => fill.envelope.name === "[Unallocated]");
  $: notUnallocated = fills.filter(
    fill => fill.envelope.name !== "[Unallocated]"
  );

  let interval = localStorage.getItem('fillInterval') || "monthly";
  $: c = fill =>
    Math.round(Balances.calcAmountForPeriod(fill.envelope)[interval]);

  function persistInterval() {
    localStorage.setItem('fillInterval', interval);
  }

  async function handleSubmit() {
    const txnId = shortid.generate();
    const txns = fills
      .map((fill, i) => {
        const txn = {
          id: shortid.generate(),
          user_id: creds.userId,
          memo: "",
          date: new Date(),
          amount: fill.amount,
          label: null,
          type: "envelopeTransfer",
          txn_id: txnId,
          from_id: unallocated.envelope.id,
          to_id: fill.envelope.id
        };
        return txn;
      })
      .filter(txn => txn.amount !== 0);

    await Transactions.saveTransactions(creds, txns);
    page("/home");
  }

  onMount(() => {
    async function fetchStuff() {
      const balancesData = await Balances.loadBalances(creds);
      const newFills = balancesData.data.balances
        .filter(balance => Balances.isBalanceEnvelope(balance))
        .map(balance => ({
          id: balance.id,
          envelopeId: balance.id,
          amount: 0,
          envelope: balance
        }));
      fills = newFills;
      return newFills;
    }
    dataP = fetchStuff();
  });
</script>

{#await dataP}
    <p>Loading accounts...</p>
{:then}
    <div class="flex justify-around content">
        <form
          on:submit|preventDefault={handleSubmit}
          class="bg-white p-4 rounded border border-2 border-grey-light m-4"
        >
            <p>Unallocated: {toDollars(unallocated.envelope.balance - sumOfFills)}</p>

            <select
                bind:value={interval}
                on:change={persistInterval}
                class="border"
            >
                <option value='weekly'>Weekly</option>
                <option value='biweekly'>Biweekly</option>
                <option value='bimonthly'>Bimonthly</option>
                <option value='monthly'>Monthly</option>
                <option value='annually'>Annually</option>
            </select>

            {#each notUnallocated as fill}
                <div class="flex justify-between bubble">
                    <div>
                        <div>
                            <Balance balance={fill.envelope} adjustment={fill.amount} />

                            <button
                                class="border btn btn-secondary"
                                on:click|preventDefault={
                                    () => fill.amount = -fill.envelope.balance + c(fill)}
                            >
                                Set to {toDollars(c(fill))}
                            </button>
                        </div>

                        <div>
                            <button
                                class="border btn btn-secondary"
                                on:click|preventDefault={() => fill.amount = c(fill)}
                            >
                                Fill with {toDollars(c(fill))}
                            </button>
                        </div>

                        <div>
                            <button
                                class="border btn btn-secondary"
                                on:click|preventDefault={() => fill.amount = -fill.envelope.balance}
                            >
                                Set to 0
                            </button>
                        </div>

                        <div>
                            <p>Old Balance: {toDollars(fill.envelope.balance)}</p>
                            <span>Fill:</span>
                            <MoneyInput
                              amount={fill.amount}
                              defaultType="credit"
                              on:change={({detail}) => fill.amount = detail}
                            />
                            <p>{fill.amount}</p>
                            <p>New Balance: {toDollars(fill.envelope.balance + fill.amount)}</p>
                        </div>
                    </div> 
                </div>
            {/each}

            <input type='submit' value='Fill!' class='btn btn-primary' />
        </form>
    </div>
{:catch ex}
    <p>Error! {ex.message}</p>
{/await}
