// client/src/components/Home.tsx
import {RouteComponentProps} from '@reach/router';
import React, {useState} from 'react';
import MediaQuery from 'react-responsive';

import Balances from './Balances';
import Transactions from './Transactions';
import * as TxnGrouped from '../lib/TxnGrouped';
import {AuthStore, FlashStore} from '../store';
import { toDollars } from '../lib/pennies';

function triggerDownload(data: string) {
  var a = document.createElement("a");
  document.body.appendChild(a);
  (a as any).style = "display: none";
  const blob = new Blob([data], {type: "octet/stream"});
  const url = window.URL.createObjectURL(blob);
  a.href = url;
  a.download = 'export.csv';
  a.click();
  window.URL.revokeObjectURL(url);
}

async function exportTxns(event: React.FormEvent<any>) {
  event.preventDefault();
  if (!AuthStore.loggedIn) throw new Error('User must be logged in');
  const txnsGrouped =
    await TxnGrouped.loadTransactions(AuthStore.userId, AuthStore.apiKey, '').
      then(({data}) => data.txns_grouped);

  const dataStr =
    JSON.stringify(txnsGrouped.map((t) => ({
      date: t.date,
      amount: toDollars(t.amount),
      from: t.from_name,
      to: t.to_names,
      memo: t.memo,
      type: t.type,
      label: t.label
    })));

  triggerDownload(dataStr);
}

export default function Home(props: RouteComponentProps) {
  const [visibleTab, setVisibleTab] = useState<'accounts' | 'transactions'>('accounts');

  function setTab(tab: 'accounts' | 'transactions') {
    return function fn(event: React.FormEvent<any>) {
      event.preventDefault();
      setVisibleTab(tab);
    }
  }

  const headerCss = 'min-w-0 p-3 rounded overflow-auto bg-white border border-2 border-grey-light rounded';

  return (
    FlashStore.type === 'error' ?
      null
      :
      <>
        <MediaQuery query='(max-width: 500px)'>
          <div>
            <div>
              <button
                onClick={setTab('accounts')}
                className='link-btn link-btn-tertiary'
              >
                Accounts/Envelopes
              </button>
              <button
                onClick={setTab('transactions')}
                className='link-btn link-btn-tertiary'
              >
                Transactions
              </button>
            </div>
            { visibleTab === 'accounts' ?
              <div className={`${headerCss} content`}>
                <header className='text-xl font-bold'>Balances</header>
                <Balances />
              </div>
            : visibleTab === 'transactions' ?
              <div className={`${headerCss} content`}>
                <header className='text-xl font-bold'>Transactions</header>
                <Transactions />
              </div>
            : null
          }
          </div>
        </MediaQuery>

        <MediaQuery query='(min-width: 501px)'>
          <div className={`${headerCss} sidebar`}>
            <header className='text-xl font-bold'>Balances</header>
            <Balances />
          </div>

          <div className={`${headerCss}`}>
            <button onClick={exportTxns} className='link-btn link-btn-tertiary'>Export Transactions</button>
            <header className='text-xl font-bold'>Transactions</header>
            <Transactions />
          </div>
        </MediaQuery>
      </>
  )
}

// client/src/Home.svelte
<script>
    import page from 'page';
    import {getContext} from 'svelte';

    import Accounts from './Accounts.svelte';
    import {toDollars} from './lib/pennies';
    import * as TxnGrouped from './lib/TxnGrouped';

    const creds = getContext('creds');
    let searchTerm = '';

    let txnsGrouped;
    $: txnsGrouped = TxnGrouped.loadTransactions(creds, searchTerm);
    const numItemsPerPage = 100;
    let pageNum = 0;

    let activeTab = 'transactions';

  function triggerDownload(data) {
    var a = document.createElement("a");
    document.body.appendChild(a);
    a.style = "display: none";
    const blob = new Blob([data], { type: "octet/stream" });
    const url = window.URL.createObjectURL(blob);
    a.href = url;
    a.download = 'export.csv';
    a.click();
    window.URL.revokeObjectURL(url);
  }

  async function exportTxns(event) {
    const txnsGrouped =
      await TxnGrouped.loadTransactions(creds, '').
        then(({ data }) => data.txns_grouped);

    const dataStr =
      JSON.stringify(txnsGrouped.map((t) => ({
        date: t.date,
        amount: toDollars(t.amount),
        from: t.from_name,
        to: t.to_names,
        memo: t.memo,
        type: t.type,
        label: t.label
      })));

    triggerDownload(dataStr);
  }
</script>

<button class="btn btn-tertiary" on:click={() => activeTab = 'transactions'}>Transactions</button>
<button class="btn btn-tertiary" on:click={() => activeTab = 'accounts'}>Accounts</button>
{#if activeTab === 'transactions'}
  <input class='border w-full' bind:value={searchTerm} placeholder='Search for transactions' />

  {#await txnsGrouped}
      Loading transactions...
  {:then txns}
    <button class='btn btn-tertiary' on:click={exportTxns} type='button'>
      Export Transactions
    </button>

    {#each txns.data.txns_grouped.slice(page * numItemsPerPage, (pageNum+1) * numItemsPerPage) as txn}
      <div
        on:click={() => page(`/editTxn/${txn.txn_id}`)}
        class="flex justify-between p-3 border border-grey-light rounded mb-1"
      >
        <div class="mr-2">{txn.date}</div>
        <div class="text-left flex-1 min-w-0 mr-2">
          <div class="text-left font-bold">
            {#if txn.label}{txn.label}{:else}<span class='italic text-sm'>No Label</span>{/if} 
            {#if txn.memo}<span title={txn.memo}>((Memo))</span>{/if}
          </div>

          <div class="flex flex-1 text-xs italic">
            <span class="whitespace-no-wrap">{txn.from_name}</span>
            &nbsp;→&nbsp;
            <span
              style="text-overflow: ellipsis"
              class="whitespace-no-wrap overflow-hidden"
            >
              {txn.to_names}
            </span>
          </div>
        </div>

        <div class="text-right">{toDollars(txn.amount)}</div>
      </div>
    {/each}

    {#each new Array(Math.ceil(txns.data.txns_grouped.length / numItemsPerPage)).fill(null).map((_, i) => i) as btn_number}
        <button
            on:click|preventDefault={() => pageNum=btn_number}
            class="btn btn-secondary"
        >
            Page {btn_number + 1}
        </button>
    {/each}
  {:catch ex}
      Error loading transactions! {ex.message}
  {/await}
{:else}
  <Accounts />
{/if}
