// client/src/views/LogIn.vue
<template>
  <form @submit.prevent="onSubmit">
    <div :value="isSuccess" type="success">You've logged in!</div>
    <div :value="formError" type="error">{{ formError }}</div>

    <label>Email</label>
    <input v-model="email" type="email" />
    <label>Password</label>
    <input v-model="password" type="password" />

    <button type="submit">Log In</button>
  </form>
</template>

<script lang="ts">
import axios from 'axios';
import Vue from 'vue';

import {endpoint} from '@/lib/config';

export default Vue.extend({
  data() {
    return {
      email: '',
      password: '',
      formError: null as string | null,
      isSuccess: false,
    };
  },

  methods: {
    async onSubmit() {
      this.formError = null;

      try {
        await axios.post(
          `${endpoint}/login`,
          {email: this.email, password: this.password},
        );
        this.isSuccess = true;
        window.location.href = '/';
      } catch (ex) {
        if (!ex.response) {
          this.formError = 'Unknown error submitting form';
          return;
        }
        console.log(ex.response);
        console.log(ex.response.status, ex.response.data);
        this.formError = ex.response.data.error;
      }
    },
  },
});
</script>

// client/src/Login.svelte
<script>
    import axios from 'axios';
    import {getContext} from 'svelte';

    const endpoint = getContext('endpoint');
    let error = null;
    let email = '';
    let password = '';

    async function handleSubmit() {
        try {
            await axios.post(
                `${endpoint}/login`, {email, password}, {withCredentials: true}
            );
            location.href = '/';  // Force the new context to get set
        } catch (ex) {
            error = ex.response.data.error;
        }
    }
</script>

<form on:submit|preventDefault={handleSubmit}>
    <header class="font-bold">Log In</header>

    {#if error}<p class='error'>{error}</p>{/if}

    <label>
        Username:
        <input
            type="email"
            placeholder="username"
            class="border w-full"
            bind:value={email}
            required
        />
    </label>

    <label>
        Password
        <input
            type="password"
            placeholder="password"
            class="border w-full"
            bind:value={password}
            required
        />
    </label>

    <button type="submit" class='btn btn-primary'>Log In</button><button>
</form>
