// client/src/components/Home.tsx
import {RouteComponentProps} from '@reach/router';
import React, { Component, useEffect, useState } from 'react';

import '../App.css';
import Balances from './Balances';
import Transactions from './Transactions';

export default function Home(props: RouteComponentProps) {
  return (
    <div style={{display: 'flex'}}>
      <h1>Balances</h1>
      <Balances />
      <h1>Transactions</h1>
      <Transactions />
    </div>
  )
}

// client/src/views/Home.vue
<template>
  <div id="home">
    <AccountBalances id="balances" />
    <Transactions id="transactions" />
  </div>
</template>

<script lang="ts">
import Vue from 'vue';

import AccountBalances from '../components/AccountBalances.vue';
import Transactions from '../components/Transactions.vue';

export default Vue.extend({
  name: 'home',
  components: {
    AccountBalances,
    Transactions,
  },
});
</script>

<style>
#home {
  display: flex;
  justify-content: space-evenly;
}

#balances {
  flex-basis: 34%;
}

#transactions {
  flex-basis: 66%;
}
</style>
