// client/src/components/Transactions.vue
<template>
  <div>
    <h1>Transactions</h1>
    <table>
      <tr v-for="txnTuple in transactions" :key="txnTuple.transaction.id">
        <td>{{ txnTuple.transaction.date }}</td>
        <td>{{ txnTuple.transaction.amount }}</td>
        <td>{{ txnTuple.transaction.label }}</td>
        <td>{{ txnTuple.transaction.memo }}</td>
        <td>{{ Array.from(new Set(txnTuple.buckets.filter(Boolean).map((bucket) => bucket.name))).join(', ') }}</td>
      </tr>
    </table>
  </div>
</template>

<script lang="ts">
import Vue from 'vue';
import * as CommonTypes from '../../../common/lib/types';

export default Vue.extend({
  computed: {
    transactions(): CommonTypes.ITransaction[] {
      return this.$store.getters['transactions/transactions'];
    }
  }
});
</script>

// src/views/Transactions.tsx
import {inject, observer} from 'mobx-react';
import * as React from 'react';

import Store from '../store';

@inject('store')
@observer
export default class Transactions extends React.Component<{store?: Store}> {
  public render() {
    return (
      <div className='container'>
        <table>
          <tbody>
            {this.props.store!.transactionsByDate.map((txn) =>(
              <tr key={txn.id}>
                <td>{txn.date.toJSON()}</td>
                <td>{txn.payee}</td>
                <td>{txn.from.name} ⇨ {txn.to.map((to) => to.bucket.name).join(', ')}</td>
                <td>{txn.memo}</td>
                <td>{txn.amount.dollars}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    );
  }
}
