// client.vue/src/views/Home.vue
<template>
  <div class="m-3">
    <div class="shadow-md p-3 rounded-lg mb-3 bg-white max-w-sm">
      Sort by:
      <select v-model="sortBy">
        <option value="name">Name</option>
        <option value="balance">Balance</option>
        <option value="period-over-period">Period-Over-Period</option>
      </select>
    </div>

    <div class="shadow-md p-3 rounded-lg mb-3 bg-white max-w-sm">
      <header
        class="font-bold text-lg small-caps cursor-pointer"
        @click="toggleShowAccounts"
      >
        <span>›</span> Accounts
      </header>
    </div>
    <div v-if="showAccounts" class="flex flex-wrap -m-3">
      <router-link
        :to="{ name: 'account', params: { accountId: account.id } }"
        v-for="{ account, balances } in accountBalances"
        :key="account.id"
        style="display: contents;"
      >
        <Balance
          :amounts="balances"
          :name="account.name"
          :defaultDaysToRender="16"
          :account="account"
        />
      </router-link>
    </div>

    <div class="shadow-md p-3 rounded-lg mb-3 bg-white max-w-sm">
      <header class="font-bold text-lg small-caps cursor-pointer">
        Envelopes
      </header>
      Group by:
      <select v-model="sortTag">
        <option :value="null">No Tag</option>
        <option v-for="tag in this.allTags" :key="tag" :value="tag">{{
          tag
        }}</option>
      </select>
    </div>

    <div v-for="tagValue in envelopeTagValues" :key="tagValue">
      <header class="small-caps">
        {{ sortTag || 'No tag selected' }}:
        <span class="font-bold small-caps">{{
          tagValue === 'null' ? 'No Value' : tagValue
        }}</span>
      </header>
      <div>Total balance: {{ toDollars(totalBalancesByTag[tagValue]) }}</div>
      <div class="flex flex-wrap -m-3">
        <router-link
          :to="{ name: 'account', params: { accountId: account.id } }"
          v-for="{ account, balances } in envelopesByTag[tagValue]"
          :key="account.id"
          style="display: contents;"
        >
          <Balance
            :amounts="balances"
            :name="account.name"
            :defaultDaysToRender="16"
            :account="account"
          />
        </router-link>
      </div>
    </div>
  </div>
</template>

<style>
.small-caps {
  font-variant: small-caps;
}
</style>

<script lang="ts">
import tinydate from 'tinydate';
import flatten from 'lodash/flatten';
import fromPairs from 'lodash/fromPairs';
import groupBy from 'lodash/groupBy';
import uniq from 'lodash/uniq';
import Vue from 'vue';

import { IAccount, Balance as BalanceT, TxnGrouped } from '../lib/types';
import Balance from '../components/Balance.vue';
import { toDollars } from '../lib/pennies';

function calcDaysInPeriod(
  periodStart: Date,
  days = [],
  periodEnd = new Date()
) {
  const nextDate = new Date(periodStart.getTime() + 86400000);
  if (nextDate > periodEnd) return days;
  return calcDaysInPeriod(nextDate, [...days, nextDate], periodEnd);
}

export default Vue.extend({
  name: 'home',
  components: {
    Balance
  },
  computed: {
    daysToRender() {
      return 16;
    },

    sortFn() {
      const currentDateStr = tinydate('{YYYY}-{MM}-{DD}')(new Date());
      return {
        name: (a, b) => (a.account.name < b.account.name ? -1 : 1),
        balance: (a, b) =>
          a.balances[currentDateStr] < b.balances[currentDateStr] ? -1 : 1,
        'period-over-period': (a, b) => {
          const datesToRender = calcDaysInPeriod(
            new Date(new Date().getTime() - 86400000 * this.daysToRender)
          );
          const amountsArrA = datesToRender.map(
            date => a.balances[tinydate('{YYYY}-{MM}-{DD}')(date)] || 0
          );
          const diffA = amountsArrA[amountsArrA.length - 1] - amountsArrA[0];

          const amountsArrB = datesToRender.map(
            date => b.balances[tinydate('{YYYY}-{MM}-{DD}')(date)] || 0
          );
          const diffB = amountsArrB[amountsArrB.length - 1] - amountsArrB[0];

          console.log(diffA, diffB);
          return diffA < diffB ? -1 : 1;
        }
      }[this.sortBy];
    },

    accountBalances() {
      return this.$store.getters.accountBalances.slice().sort(this.sortFn);
    },
    envelopeBalances() {
      return this.$store.getters.envelopeBalances.slice().sort(this.sortFn);
    },

    allTags() {
      return uniq(
        flatten(
          this.envelopeBalances.map(envelope =>
            Object.keys(envelope.account.tags)
          )
        ).sort()
      );
    },
    /**
     * Returns the envelopes grouped under their value for the active tag
     */
    envelopesByTag(): {[tag: string]: {account: IAccount, balances: {[date: string]: number}}} {
      return groupBy(this.envelopeBalances, envelope =>
        this.sortTag ? envelope.account.tags[this.sortTag] : null
      );
    },
    envelopeTagValues(): string[] {
      return Object.keys(this.envelopesByTag).sort();
    },

    totalBalancesByTag() {
      return fromPairs(
        Object.entries<
          {
            account: IAccount;
            balances: { [date: string]: number };
          }[]
        >(this.envelopesByTag).map(([tag, envelopeBalances]) => {
          const currentDateStr = tinydate('{YYYY}-{MM}-{DD}')(new Date());
          return [
            tag,
            envelopeBalances
              .map(({ balances }) => balances[currentDateStr])
              .reduce(
                (tagBalance, envelopeBalance) => tagBalance + envelopeBalance,
                0
              )
          ];
        })
      );
    }
  },
  data() {
    return {
      toDollars,
      showAccounts: false,
      sortBy: 'name',
      sortTag: null
    };
  },
  methods: {
    toggleShowAccounts() {
      this.showAccounts = !this.showAccounts;
    }
  }
});
</script>

// client.react/src/views/Home.tsx
import { Observer } from "mobx-react";
import { useLocalStore } from "mobx-react-lite";
import * as R from "ramda";
import React, { useContext } from "react";
import { Link } from "react-router-dom";

import { formatDate } from "../lib/utils";
import { toDollars } from "../lib/pennies";

import StoreContext, { AccountBalance } from "../store";
import Balance from "../components/Balance";

const sortFns = {
  name: (a: AccountBalance, b: AccountBalance) =>
    a.account.name < b.account.name ? -1 : 1,
  balance: (a: AccountBalance, b: AccountBalance) => {
    const currentDateStr = formatDate(new Date());
    return a.balances[currentDateStr] < b.balances[currentDateStr] ? -1 : 1;
  }
  /*
  'period-over-period': (a, b) => {
    const datesToRender = calcDaysInPeriod(
      new Date(new Date().getTime() - 86400000 * this.daysToRender)
    );
    const amountsArrA = datesToRender.map(
      date => a.balances[tinydate('{YYYY}-{MM}-{DD}')(date)] || 0
    );
    const diffA = amountsArrA[amountsArrA.length - 1] - amountsArrA[0];

    const amountsArrB = datesToRender.map(
      date => b.balances[tinydate('{YYYY}-{MM}-{DD}')(date)] || 0
    );
    const diffB = amountsArrB[amountsArrB.length - 1] - amountsArrB[0];

    console.log(diffA, diffB);
    return diffA < diffB ? -1 : 1;
  }
   */
};

export default function Home() {
  const store = useContext(StoreContext);
  const localStore = useLocalStore(() => ({
    sortBy: "name" as keyof typeof sortFns,
    sortTag: null as string | null,
    showAccounts: false as boolean
  }));

  console.log(store.transactions);
  return (
    <Observer>
      {() => {
        const sortFn = sortFns[localStore.sortBy];
        const accountBalances = store.accountBalances.slice().sort(sortFn);
        const envelopeBalances = store.envelopeBalances.slice().sort(sortFn);
        const allTags: string[] = R.uniq(
          R.chain(
            envelope => Object.keys(envelope.account.tags),
            envelopeBalances
          ).sort()
        );

        const envelopesByTag: { [tag: string]: AccountBalance[] } = R.groupBy(
          envelope =>
            localStore.sortTag ? envelope.account.tags[localStore.sortTag] : "",
          envelopeBalances
        );

        const envelopeTagValues: string[] = Object.keys(envelopesByTag).sort();

        const totalBalancesByTag = R.fromPairs(
          Object.entries(envelopesByTag).map(([tag, envelopeBalances]) => {
            const currentDateStr = formatDate(new Date());
            return [
              tag,
              envelopeBalances
                .map(({ balances }) => balances[currentDateStr])
                .reduce(
                  (tagBalance, envelopeBalance) => tagBalance + envelopeBalance,
                  0
                )
            ];
          })
        );

        return (
          <div className="m-3">
            <div className="shadow-md p-3 rounded-lg mb-3 b-white max-w-sm">
              Sort by:
              <select
                onChange={event =>
                  (localStore.sortBy = event.target
                    .value as keyof typeof sortFns)
                }
              >
                <option value="name">Name</option>
                <option value="balance">Balance</option>
              </select>
            </div>

            <div className="shadow-md p-3 rounded-lg mb-3 bg-white max-w-sm">
              <header
                className="font-bold text-lg small-caps cursor-pointer"
                onClick={() =>
                  (localStore.showAccounts = !localStore.showAccounts)
                }
              >
                <span>›</span> Accounts
              </header>
            </div>

            {localStore.showAccounts ? (
              <div className="flex flex-wrap -m-3">
                {accountBalances.map(balance => (
                  <Link
                    to={`/account/${encodeURIComponent(balance.account.id)}`}
                    style={{ display: "contents" }}
                    key={balance.account.id}
                  >
                    <Balance balance={balance} defaultDaysToRender={15} />
                  </Link>
                ))}
              </div>
            ) : null}

            <div className="shadow-md p-3 rounded-lg mb-3 bg-white max-w-sm">
              <header className="font-bold text-lg small-caps cursor-pointer">
                Envelopes
              </header>
              Group by:
              <select
                onChange={event => (localStore.sortTag = event.target.value)}
              >
                <option value={"null"}>No Tag</option>
                {allTags.map(tag => (
                  <option key={tag} value={tag}>
                    {tag}
                  </option>
                ))}
              </select>
            </div>

            {envelopeTagValues.map(tagValue => (
              <div key={tagValue}>
                <header className="small-caps">
                  {localStore.sortTag || "No tag selected"}:
                  <span className="font-bold small-caps">
                    {tagValue === "" ? "No Value" : tagValue}
                  </span>
                </header>
                <div>
                  Total balance: {toDollars(totalBalancesByTag[tagValue])}
                </div>
                <div className="flex flex-wrap -m-3">
                  {envelopesByTag[tagValue].map(balance => (
                    <Link
                      to={`/account/${encodeURIComponent(balance.account.id)}`}
                      style={{ display: "contents" }}
                      key={balance.account.id}
                    >
                      <Balance
                        balance={balance}
                        defaultDaysToRender={15}
                        key={balance.account.id}
                      />
                    </Link>
                  ))}
                </div>
              </div>
            ))}
          </div>
        );
      }}
    </Observer>
  );
}
