// client/src/EditTags.svelte
<script>
  import fromPairs from 'lodash/fromPairs';
  import page from 'page';
  import {getContext, onMount} from 'svelte';
  
  import * as Accounts from './lib/Accounts';
  import * as Tags from './lib/Tags';

  const graphql = getContext('graphql');
  let initializeP = new Promise(() => null);
  let allTags = [];
  let accounts = [];
  let selectedTag = null;
  let error = null;

  onMount(() => {
    async function initialize() {
      const {data: tags} = await Tags.loadTags(graphql);
      allTags = tags.tags.map(({tag}) => tag);

      const {data: accountsData} = await Accounts.loadAccounts(graphql);
      accounts =
        accountsData.accounts.
        filter(Accounts.isEnvelope).
        sort((a, b) => a.name < b.name ? -1 : 1);
    }

    initializeP = initialize();
  });

  async function handleSubmit() {
    const accountsWithSelectedTag = fromPairs(
      accounts.
      filter((account) => account.tags[selectedTag]).
      map((account) => [account.id, {[selectedTag]: account.tags[selectedTag]}])
    );

    const accountsWithoutSelectedTag =
      accounts.
      filter((account) => !account.tags[selectedTag]).
      map((account) => account.id);
  
    try {
      await Tags.updateAccountsTags(graphql, accountsWithSelectedTag)
      await Tags.deleteTagFromAccounts(graphql, selectedTag, accountsWithoutSelectedTag);
      error = null;
      page('/home');
    } catch (ex) {
      error = ex.message;
      throw ex;
    }
  }
</script>

{#await initializeP}
  <p>Loading...</p>
{:then}
  <div class='flex justify-around'>
    {#if error}<p>{error}</p>{/if}

    <form on:submit|preventDefault={handleSubmit} class='content'>
      <select bind:value={selectedTag} class='border'>
        <option value={null}>Select a tag</option>
        {#each allTags as tag}
          <option value={tag}>{tag}</option>
        {/each}
      </select>

      {#if selectedTag}
        {#each accounts as account}
          <div>
            <label class='label'>
              {account.name}
              <input
                class='input'
                value={account.tags[selectedTag] || ''}
                on:input={(event) => account.tags[selectedTag] = event.target.value}
              />
            </label>
          </div>
        {/each}

        <div>
          <button type="submit" class='btn btn-primary'>Save Tags</button>
        </div>
      {/if}
    </form>
  </div>
{:catch ex}
  <p>Error! {ex.message}</p>
{/await}

// client/src/components/EditTags.tsx
import fromPairs from 'lodash/fromPairs';
import { Observer, useLocalStore } from "mobx-react-lite"
import React from 'react';
import { RouteComponentProps } from 'react-router-dom';
import {useEffect} from 'react';

import * as Accounts from '../lib/Accounts';
import { AuthStore } from '../store';
import * as Tags from '../lib/Tags';

export default function EditTags(props: RouteComponentProps<{}>) {
  const store = useLocalStore(() => ({
    selectedTag: null as string | null,
    envelopes: [] as Accounts.Envelope[],
    error: null as string | null,
    tags: [] as string[],
    setTags(tags: string[]) {
      this.tags = tags;
    },
    setEnvelopes(envelopes: Accounts.Envelope[]) {
      this.envelopes = envelopes;
    },
  }));

  useEffect(() => {
    async function fetchData() {
      if (!AuthStore.loggedIn) throw new Error('User must be logged in');
      const {data: tags} = await Tags.loadTags(AuthStore.userId, AuthStore.apiKey);
      store.setTags(tags.tags.map(({tag}) => tag));

      const {data: accounts} = await Accounts.loadAccounts(AuthStore.userId, AuthStore.apiKey);
      store.setEnvelopes(
        accounts.accounts
        .filter(Accounts.isEnvelope)
        .sort((a, b) => a.name < b.name ? -1 : 1)
      );
    }

    fetchData();
  }, [store]);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();

    const selectedTag = store.selectedTag;
    if (selectedTag === null) {
      store.error = 'Must select a tag before saving';
      return;
    }
    const accountsWithSelectedTag = fromPairs(
      store.envelopes
      .filter((account) => account.tags[selectedTag])
      .map((account) => [account.id, {[selectedTag]: account.tags[selectedTag]}])
    );

    const accountsWithoutSelectedTag =
      store.envelopes
      .filter((account) => !account.tags[selectedTag])
      .map((account) => account.id);
  
    if (!AuthStore.userId || !AuthStore.loggedIn) {
      store.error = 'Must be logged in';
      return;
    }
    try {
      await Tags.updateAccountsTags(AuthStore, accountsWithSelectedTag)
      await Tags.deleteTagFromAccounts(AuthStore, selectedTag, accountsWithoutSelectedTag);
      store.error = null;
      props.history.push('/');
    } catch (ex) {
      store.error = ex.message;
      throw ex;
    }  }

  return <div className='flex justify-around'>
    {store.error ? <p>store.error</p> : null}

    <Observer>{() =>
      <form onSubmit={handleSubmit}>
        <select
          value={store.selectedTag || ''}
          onChange={(event) => store.selectedTag = event.target.value}
          className='border'
        >
          <option value={''}>Select a tag</option>
          {store.tags.map((tag) => <option value={tag} key={tag}>{tag}</option>)}
        </select>

        {store.selectedTag === null ? null : 
          <>
            {store.envelopes.map((envelope) =>
              <div key={envelope.id}>
                <label className='label'>
                  {envelope.name}
                  <input
                    className='input'
                    value={envelope.tags[store.selectedTag!] || ''}
                    onChange={(event) => envelope.tags[store.selectedTag!] = event.target.value}
                  />
                </label>
              </div>
            )}

            <div>
              <button type='submit' className='link-btn link-btn-primary'>Save Tags</button>
            </div>
          </>
        }
      </form>
    }</Observer>
  </div>
}
