// client/src/Login.svelte
<script>
    import axios from 'axios';
    import {getContext} from 'svelte';

    const endpoint = getContext('endpoint');
    let error = null;
    let email = '';
    let password = '';

    async function handleSubmit() {
        try {
            await axios.post(
                `${endpoint}/login`, {email, password}, {withCredentials: true}
            );
            location.href = '/';  // Force the new context to get set
        } catch (ex) {
            error = ex.response.data.error;
        }
    }
</script>

<form on:submit|preventDefault={handleSubmit}>
    <header class="font-bold">Log In</header>

    {#if error}<p class='error'>{error}</p>{/if}

    <label>
        Username:
        <input
            type="email"
            placeholder="username"
            class="border w-full"
            bind:value={email}
            required
        />
    </label>

    <label>
        Password
        <input
            type="password"
            placeholder="password"
            class="border w-full"
            bind:value={password}
            required
        />
    </label>

    <button type="submit" class='btn btn-primary'>Log In</button><button>
</form>

// client/src/components/LogIn.tsx
import axios from 'axios';
import {RouteComponentProps} from 'react-router-dom';
import React, {useState} from 'react';

import {AuthStore} from '../store';
import {endpoint} from '../lib/config';

function LogIn(props: RouteComponentProps) {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState<string | null>(null);

  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();

    try {
      const response = await axios.post(`${endpoint}/login`, {email: username, password});
      setError(null);
      AuthStore.loggedIn = true;
      AuthStore.userId = response.data.userId;
      AuthStore.apiKey = response.data.apikey;
      props.history.push('/');
    } catch (ex) {
      setError(ex.response.data.error);
    }
  }

  const style: React.CSSProperties = {
    backgroundColor: 'white',
    padding: '24px',
    borderRadius: '8px',
    border: '2px solid #e1e1e1',
    margin: '24px',
  }

  return (
    <>
      {error ? <p>{error}</p> : null}
      <form style={style} onSubmit={handleSubmit}>
        <header style={{fontWeight: 'bold'}}>Log In</header>
        <label>
          Username
          <input
            type="email"
            placeholder='username'
            value={username}
            onChange={(event) => setUsername(event.target.value)}
            className='border w-full'
          />
        </label>
        <label>
          Password
          <input
            type="password"
            placeholder='password'
            value={password}
            onChange={(event) => setPassword(event.target.value)}
            className='border w-full'
          />
        </label>

        <button type="submit" className='link-btn link-btn-primary'>Log In</button>
      </form>
    </>
  );
}

export default LogIn;
